export const WALLET_CONNECTED = "WALLET_CONNECTED";
export const WALLET_DISCONNECTED = "WALLET_DISCONNECTED";

export const CREATE_INSURANCE_REQUEST = "CREATE_INSURANCE_REQUEST";
export const CREATE_INSURANCE_SUCCESS = "CREATE_INSURANCE_SUCCESS";
export const CREATE_INSURANCE_FAILURE = "CREATE_INSURANCE_FAILURE";

export const UPDATE_INSURANCE_REQUEST = "UPDATE_INSURANCE_REQUEST";
export const UPDATE_INSURANCE_SUCCESS = "UPDATE_INSURANCE_SUCCESS";
export const UPDATE_INSURANCE_FAILURE = "UPDATE_INSURANCE_FAILURE";

export const FETCH_INSURANCE_REQUEST = "FETCH_INSURANCE_REQUEST";
export const FETCH_INSURANCE_SUCCESS = "FETCH_INSURANCE_SUCCESS";
export const FETCH_INSURANCE_FAILURE = "FETCH_INSURANCE_FAILURE";

export const CLAIM_INSURANCE_REQUEST = "CLAIM_INSURANCE_REQUEST";
export const CLAIM_INSURANCE_SUCCESS = "CLAIM_INSURANCE_SUCCESS";
export const CLAIM_INSURANCE_FAILURE = "CLAIM_INSURANCE_FAILURE";

export const CONNECT_MINUT_ACCOUNT_REQUEST = "CONNECT_MINUT_ACCOUNT_REQUEST";
export const CONNECT_MINUT_ACCOUNT_SUCCESS = "CONNECT_MINUT_ACCOUNT_SUCCESS";
export const CONNECT_MINUT_ACCOUNT_FAILURE = "CONNECT_MINUT_ACCOUNT_FAILURE";

export const NEW_USER_CONNECTED = "NEW_USER_CONNECTED";
